# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: AI Engineering Academy
site_url: https://aiengineering.academy
site_author: Adithya S Kolavi
site_description: >-
  Mastering Applied AI, One Concept at a Time

# Repository
repo_name: adithya-s-k/AI-Engineering.academy
repo_url: https://github.com/adithya-s-k/AI-Engineering.academy

# Copyright
copyright: Copyright &copy; 2024 - 2025 Adithya S Kolavi

# Configuration
theme:
  name: material
  # custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - mkdocs-jupyter:
      include_source: true
      ignore_h1_titles: true
      execute: false
      allow_errors: true
      ignore_patterns:
        - "archives/*"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adithya-s-k/AI-Engineering.academy
    - icon: fontawesome/brands/python
      link: https://github.com/adithya-s-k/AI-Engineering.academy
    # - icon: fontawesome/brands/bluesky
    #   link:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/adithya_s_k

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree

nav:
  - Home: README.md
  - Prompt Engineering:
      - Introduciton: PromptEngineering/README.md
      - Understanding OpenAI API: PromptEngineering/Understanding_OpenAI_API.md
      - Basic Prompt Engineering: PromptEngineering/Basic_Prompting.md
      - Advance Prompt Engineering: PromptEngineering/Advanced_Prompting.md
      - Prompting Hands On: PromptEngineering/prompt_engineering.ipynb
      - Function Calling: PromptEngineering/function_calling.ipynb
      - Hands on with Adv Prompting: PromptEngineering/hand_on_with_advanced_prompt_engineering.md
  - RAG:
      - Introduction: RAG/README.md
      - Embedding and Similarity:
          - Introduction: RAG/00_RAG_from_Scratch/Understanding_embeddings_and_similarity.ipynb
      - RAG Techniques:
          - RAG from Scratch:
              - Overview: RAG/00_RAG_from_Scratch/README.md
              - Implementation: RAG/00_RAG_from_Scratch/RAG_in_10_lines.ipynb
          - Basic RAG:
              - Overview: RAG/01_Basic_RAG/README.md
              - Implementation: RAG/01_Basic_RAG/notebook.ipynb
              - Evaluation: RAG/01_Basic_RAG/notebook_eval.ipynb
          - BM25 RAG:
              - Overview: RAG/01_BM25_RAG/README.md
              - Implementation: RAG/01_BM25_RAG/notebook.ipynb
          - Data Ingestion:
              - Data Chunking: RAG/01_Data_Ingestion/data_chunking.ipynb
              - Data Embedding: RAG/01_Data_Ingestion/data_embedding.ipynb
              - Data Ingestion: RAG/01_Data_Ingestion/data_ingestion.ipynb
          - RAG Evaluation:
              - Overview: RAG/01_RAG_Evaluation/README.md
              - RAGAS: RAG/01_RAG_Evaluation/RAGAS.ipynb
              - DeepEval: RAG/01_RAG_Evaluation/deepeval.ipynb
              - TruLens: RAG/01_RAG_Evaluation/trulens.ipynb
              - Notebook: RAG/01_RAG_Evaluation/notebook.ipynb
          - RAG Observability:
              - Overview: RAG/01_RAG_Observability/README.md
              - Implementation: RAG/01_RAG_Observability/notebook.ipynb
          - ReRanker RAG:
              - Implementation: RAG/02_ReRanker_RAG/notebook.ipynb
              - Evaluation: RAG/02_ReRanker_RAG/notebook_eval.ipynb
          - Hybrid RAG:
              - Qdrant Hybrid Search: RAG/03_Hybrid_RAG/_Qdrant_Hybrid_Search.ipynb
              - Implementation: RAG/03_Hybrid_RAG/qdrant_hybrid.ipynb
          - Sentence Window RAG:
              - Implementation: RAG/04_Sentence_Window_RAG/Sentence_window_retrieval.ipynb
          - Auto Merging RAG:
              - Implementation: RAG/05_Auto_Merging_RAG/Auto-merging_Retrieval.ipynb
          - HyDE RAG:
              - Implementation: RAG/06_HyDE_RAG/HyDEQueryTransformDemo.ipynb
          - Query Transformation RAG:
              - Implementation: RAG/06_Query_Transformation_RAG/query_transform_cookbook.ipynb
          - Self Query RAG:
              - Implementation: RAG/07_Self_Query_RAG/Self_Query_RAG.ipynb
          - RAG Fusion:
              - Implementation: RAG/08_RAG_Fusion/ragfusion.ipynb
          - RAPTOR:
              - Implementation: RAG/09_RAPTOR/raptor.ipynb
          - ColBERT RAG:
              - Implementation: RAG/10_ColBERT_RAG/ColBert_RAG.ipynb
              - Ragatouille Retriever: RAG/10_ColBERT_RAG/ragatouille_retriever.ipynb
          - Graph RAG:
              - Implementation: RAG/11_Graph_RAG/GraphRAG_v1.ipynb
          - Agentic RAG:
              - Implementation: RAG/12_Agnetic_RAG/multi_document_agents.ipynb
          - Vision RAG:
              - Implementation: RAG/13_Vision_RAG/gpt4v_multi_modal_retrieval.ipynb
  - LLM:
      - Introduction: LLM/README.md
      - GRPO Finetuning:
          - Overview: LLM/GRPO/hacker_guide_to_GRPO.md
          - Implementation: LLM/GRPO/Qwen_0_5b__GRPO.ipynb
      - LLM:
          - Gemma:
              - Overview: LLM/Gemma/README.md
              - Implementation: LLM/Gemma/Gemma_finetuning_notebook.ipynb
          - Llama2:
              - Overview: LLM/LLama2/README.md
              - Implementation: LLM/LLama2/Llama2_finetuning_notebook.ipynb
              - QLora: LLM/LLama2/Llama_2_Fine_Tuning_using_QLora.ipynb
          - Llama3: LLM/Llama3_finetuning_notebook.ipynb
          - Mistral:
              - Overview: LLM/Mistral-7b/README.md
              - Implementation: LLM/Mistral-7b/Mistral_finetuning_notebook.ipynb
              - Evaluation: LLM/Mistral-7b/LLM_evaluation_harness_for_Arc_Easy_and_SST.ipynb
              - DPO Fine-tuning: LLM/Mistral-7b/notebooks_DPO_fine_tuning.ipynb
              - SFT Trainer: LLM/Mistral-7b/notebooks_SFTTrainer TRL.ipynb
              - ChatML Inference: LLM/Mistral-7b/notebooks_chatml_inference.ipynb
          - Mixtral: LLM/Mixtral/Mixtral_fine_tuning.ipynb
      - VLM:
          - Florence2: LLM/VLM/Florence2_finetuning_notebook.ipynb
          - PaliGemma: LLM/VLM/PaliGemma_finetuning_notebook.ipynb
      - LLM Architecture:
          - Parameter Count: LLM/LLMArchitecture/ParameterCount/README.md
  - Deployment:
      - Introduction: Deployment/README.md
      - Deploy LLM:
          - Overview: Deployment/DeployLLM/README.md
      - Quantization:
          - AWQ: Deployment/Quantization/AWQ_Quantization.ipynb
          - GGUF: Deployment/Quantization/GGUF_Quantization.ipynb
  - Agents:
      - Overview: Agents/README.md
      - Patterns:
          - Reflection Pattern: Agents/patterns/reflection_pattern.ipynb
          - Tool Pattern: Agents/patterns/tool_pattern.ipynb
          - Planning Pattern: Agents/patterns/planning_pattern.ipynb
          - Multi-Agent Pattern: Agents/patterns/multiagent_pattern.ipynb
      - Projects:
          - Multi-Document Agents: Agents/projects/multi_document_agents.ipynb
  - Projects:
      - Introduction: Projects/README.md
      - YouTube Clones:
          - Overview: Projects/YT_Clones/README.md
          - Fireship Clone: Projects/YT_Clones/Fireship_clone.ipynb
          - Dataset Preparation: Projects/YT_Clones/dataset_prep.ipynb
  - Blog:
      - blog/index.md
